jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8083
   servlet:
      context-path: /meta-recomendador
      session:
         timeout: 21600s

spring:
   datasource:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:sqlserver://34.133.246.146;databaseName=recomendadordb
      username: sqlserver
      password: admin
      hikari:
         poolName: pool

