runtime: java11
instance_class: F2
entrypoint: java -jar meta-recomendador-0.0.1-SNAPSHOT.jar

env_variables:
  CLOUD_SQL_USERNAME: sqlserver
  CLOUD_SQL_PASSWORD: admin
  CLOUD_SQL_DATABASE_NAME: recomendadordb
  CLOUD_SQL_CONNECTION_NAME: metarecomendador:us-central1:metarecomendadordb